# Exercise 2: Associative memory

## 2.1 Forming the correlation matrix directly

In this part of the exercise we will use the direct approach in forming the correlation matrix. Memory based on the correlation matrix should memorize input-output association pairs represented as vectors. For each input vector (key) the memory has to memorize the output pattern i.e. vector in an ASCII code formulation. In this example we will use 4-dimensional input and output vectors. Words (output vectos) that have to be memorized are: '*vrat*' , '*kraj*' , '*cres*' , '*otac*'. Vectors $b_i$, which represent those words should be formed as follows:

In [ ]:
import numpy as np

real=lambda x: np.array([[ord(character) for character in x]]).T


b1=real("vrat")
b2=real("kraj")
b3=real("cres")
b4=real("otac")

### 2.1.1 Orthogonal input vectors

This experiment demonstrates how to create an associative memory. Ortonormalized set of vectors defined as below

In [ ]:
a1 = np.array([[1, 0, 0, 0]]).T
a2 = np.array([[0, 1, 0, 0]]).T
a3 = np.array([[0, 0, 1, 0]]).T
a4 = np.array([[0, 0, 0, 1]]).T

#a1 = np.array([[1, 1, 0, 0]]).T
#a2 = np.array([[0, 1, 0, 0]]).T
#a3 = np.array([[0, 0, 1, 0]]).T
#a4 = np.array([[0, 0, 0, 1]]).T

is used as input vector set (set of keys). We form the memory correlation matrix $\mathbf{M}$ using input output pairs as follows:

In [ ]:
M = b1 * a1.T + b2 * a2.T + b3 * a3.T + b4 * a4.T
print(M)

In order to verify whether the memory is functioning properly, we have to calculate outputs for each input vector. For example, the output for the key $a_1$ can be obtained as follows:

In [ ]:
char=lambda x:"".join(map(chr, map(int, list(x))))

word=char(M@a1)
print(word)

**Tasks**

1. What is the response for each key? Were all input-output pairs memorized correctly?
2. How many input-output pairs would be memorized if vectors $a_i$ were not normalized?

In [ ]:
for k in [a1, a2, a3, a4]:
    print(k.T, char(M@k))

Sve riječi su dobro zapamćene. Ako promjenimo matricu i onda pokušamo ponoviti postupak nećemo dobiti spremljlene riječi nego niz raznih simbola poput:

[[1 1 1 0]] ̠̊ʫ̆

[[0 1 1 0]] ʔʮɊʒ

[[0 0 1 0]] ńŖħő

[[0 1 0 1]] ƿnjƄƤ

Svejedno pamti 4 para ulaz izlaz ali ih ne pamti dobro.

### 2.1.2 Correlation matrix properties

The goal of this experiment is to demonstrate the capacity of obtained memory. In this part of the exercise we will try to memorize one more (fifth) word ('*mrak*'). In 4-dimensional vector space the maximum number of linearly independent vectors is four. Because of this fact, we pick an arbitrary unit vector as the fifth key, for example:

In [ ]:
a5 = (a1 + a3) / np.sqrt(2)

Form vectors $b_5$ ('*mrak*') and $a_5$ as explained and add them into the memory using the following expression:

In [ ]:
b5 = real("mrak")
M_five = b1 * a1.T + b2 * a2.T + b3 * a3.T + b4 * a4.T + b5 * a5.T

**Tasks**

1. Was the new association properly memorized?
2. Did other associations stay correctly memorized?
    - If not - which were not memorized correctly and why?
    - If yes - which were memorized correctly and why?

In [ ]:
for k in [a1, a2, a3, a4]:
    before=char(M@k)
    after=char(M_five@k)
    print(k.T, before, after)

print(a5.T, char(M_five@a5))

Riječ mrak nije bila dobro memorizirana zato jer redci u koju smo ju htjeli zapisati već sadrže informacije za riječi vrat i cres. Zbog toga što smo pokušali dodati u retke dodatne informacije izgubili smko u matrici M_five i prethodno pohranjene riječi. U redcima koje nismo dirali riječi kraj i otac su ostale zapamćene.

### 2.1.3 Word pairs as associations

In this experiment we will form the associative memory, which memorizes word pairs. The associations, which have to be memorized are: *ruka*-*vrat*, *kset*-*kraj*, *more*-*cres*, *mama*-*otac*. Generate input vectors (keys) as follows:

In [ ]:
a1 = real("ruka")
a2 = real("kset")
a3 = real("more")
a4 = real("mama")

M = b1 * a1.T + b2 * a2.T + b3 * a3.T + b4 * a4.T
print(M)

Vectors bi don't have to be created again because they are the ones used in the first part of the exercise. Form the matrix M using the same procedure as in the first part of the exercise.

**Tasks**

1. What is the response for each input key?

Za svaki kljuc program baca error zbog prevelikih brojeva, a ne postoji način da dođemo do orginal vektora.

2. Which associations were memorized correctly?

Ne možemo doći do njih tako da ni jedna.
3. Which associations were not memorized correctly and why?
Sve su bile krivo zapamćene jer ne možemo doći do njih.
4. How can we fix this problem?
Prbacujući matricu u ortonormiranu.

In [ ]:
print(M)

for k in [a1, a2, a3, a4]:
  print(k, char(M@k))

### 2.1.4 Input vector orthogonalization

In this experiment we show an associative memory, which uses keys that are orthonormalized. We use the Gram-Schmidt orthogonalization method as follows. We first form the matrix $\mathbf{A}$ using vectors $a_i$:

In [ ]:
A=np.hstack([a1, a2, a3, a4])

After this step we perform the orthonormalization step:

In [ ]:
from scipy.linalg import orth
C=orth(A.T)

We extract individual orthonormal vectors $c_i$:

In [ ]:
c1=np.array([C[0]]).T
c2=np.array([C[1]]).T
c3=np.array([C[2]]).T
c4=np.array([C[3]]).T

In the next step we form a new matrix $\mathbf{M}$ using vectors $c_i$ instead of vectors $a_i$ when creating the matrix $\mathbf{M}$. Verify the responses of matrix $\mathbf{M}$ with vectors $c_i$ as inputs:

In [ ]:
M = b1 * c1.T + b2 * c2.T + b3 * c3.T + b4 * c4.T
for c in [c1, c2, c3, c4]:
    print(c.T, char(M@c))


**Tasks**

1. What is the effect of vector orthonormalization?

Tim postupkom vektore u matrici činimo ortogonalnima ćime osiguravamo dobivanje točno pohranjenih podataka. 
2. How many pairs were correctly memorized?

Samo je prvi dio para dobro zapamćen do drugog djela ne možemo doći.
3. What can we expect when normalizing the vectors?

Možemo očekivati točne rezultate jer se rješavamo šuma u vektorima.
4. What can we expect when only orthogonalizing the vectors?

Točne rezultate osim ako se šum uvukao u vektore jer će on onda davati pogrešne rezultate.
5. What can we expect if vectors $c_i$ are linearly independent but not orthogonal? 

Da je kapacitet memorije jednak dimenziji vektora i da može doći do pogreške pri pamćenju.

### 2.1.5 Finding the correlation matrix using matrix inversion

For previously used word pairs (*ruka*-*vrat*, *kset*-*kraj*, *more*-*cres*, *mama*-*otac*) find a $4\times 4$ correlation matrix $\mathbf{M}$ as $\mathbf{M} = \mathbf{B}\mathbf{A}^{-1}$, where matrix $\mathbf{B}$ is defined as:

In [ ]:
B=np.hstack([b1, b2, b3, b4])
M=B@np.linalg.inv(A)

**Tasks**

1. Were all associations properly memorized? Remark: The result should be rounded to the nearest number before comparison.

In [ ]:
for a in [a1, a2, a3, a4]:
    print(a.T, char(np.round(M@a)))

print()

for b in [b1, b2, b3, b4]:
    print(b.T, char(np.round(M@b)))

Dobro su zapamćene samo prve riječi u paru.

### 2.1.6 Finding the correlation matrix using pseudo-inversion

A pseudo-inverse matrix can be used in order to find the correlation matrix when number of associations is larger than dimensionality of vectors representing the associations. In this case, the correlation matrix can be found as $\mathbf{M} = \mathbf{B}\mathbf{A}^{+}$, where $\mathbf{A}^{+}$ is a pseudo-inverse matrix defined as $\mathbf{A}^{+} = \mathbf{A}^{T}(\mathbf{A}\mathbf{A}^{T})^{-1}$.

Assume that the vectors $a_i$ and $b_i$ are defined previously (five associations in total). Find the pseudo-inverse matrix for this case.

In [ ]:
a1 = np.array([[1, 0, 0, 0]]).T
a2 = np.array([[0, 1, 0, 0]]).T
a3 = np.array([[0, 0, 1, 0]]).T
a4 = np.array([[0, 0, 0, 1]]).T

a5 = (a1 + a3) / np.sqrt(2)

A=np.hstack([a1, a2, a3, a4, a5])
B=np.hstack([b1, b2, b3, b4, b5])

A_pseudo=A.T@np.linalg.inv(A@A.T)
M=B@A_pseudo

print(A_pseudo@A)

**Tasks**

1. Were all pairs memorized correctly?

Ponovo je došlo do pogreške u redcima koji su sudjelovali u stvaranju a5 retka kod prve riječi apra, a kod druge ništa nije dobro zapamćeno.
2. If not, what is the error between expected and obtained values?

Pogreška je u tome što umnožak pseudo A matrice i A matrice ne daje jediničnu matricu, a to je uvjet perfektne asocijacije.

In [ ]:
for a in [a1, a2, a3, a4, a5]:
    print(a.T, char(np.round(M@a)))

for b in [b1, b2, b3, b4, b5]:
    print(b.T, char(np.round(M@b)))

## 2.2 Finding the correlation matrix using supervised learning

This experiment shows us how to form the matrix $\mathbf{M}$ using supervised learning. In two following experiments we will use learning with error correction.

### 2.2.1 Learning with error correction

Form matrices $\mathbf{A}$ and $\mathbf{B}$ where each contains 4 vectors stacked in columns as explained in previous experiments. Check the contents of obtained matrices with following operations:

In [ ]:
a1=real("ruka")
a2=real("kset")
a3=real("more")
a4=real("mama")

b1=real("vrat")
b2=real("kraj")
b3=real("cres")
b4=real("otac")

A=np.hstack([a1, a2, a3, a4])
B=np.hstack([b1, b2, b3, b4])

In order to start the learning procedure we have to initialize the matrix $\mathbf{M}$ (For example, random values uniformly generated in $[-0.5, 0.5]$ interval):

In [ ]:
M=np.random.rand(4, 4)-0.5

For the learning part use the function *trainlms*, which is the implementation of the Widrow-Hoff LMS learning algorithm. The function can be used as follows:

In [ ]:
def trainlms(A, B, M, ni, max_num_iter, min_err=0.02):
    d=B
    x=A
    w=M
    
    n=0
    err=[]
    while (n<max_num_iter):
        n+=1
        e=d-w@x
        w+=ni*np.dot(e, x.T)
        err.append(np.sum(np.sum(np.multiply(e, e))))
        if (err[-1]<min_err):
            break
    return w, err

where *max_num_iter* is the number of iterations and *ni* is the learning rate. Find the *max_num_iter* variable experimentally. For *ni* you can use:

In [ ]:
ni=0.9999/np.linalg.eig(A @ A.T)[0].max()

The function trainlms performs the learning until SSE drops below $0.02$ or maximum number of iterations is performed. After the learning phase, look at the responses of the correlation matrix $\mathbf{M}$:

In [ ]:
M, e=trainlms(A, B, M, ni, 100000)

If we type

In [ ]:
np.round(M@A)==B

we will see, which characters were properly reconstructed: the positions with correct reconstructions will have value *True* and  other positions will have value *False*. By calling the *trainlms* multiple times we can extend the learning process and maybe increase the number of memorized characters but the proper way to extend the learning process is to increase the *max_num_iter* variable. We can draw a graph, which plots the error with number of iterations (in logaritmic scale) using the following commands:

In [ ]:
import matplotlib.pyplot as plt

plt.plot(e)
plt.yscale("log")
plt.xscale("log")
plt.xlabel("Number of iterations")
plt.ylabel("Error")
plt.show()

**Tasks**

1. Plot a graph showing number of memorized characters tied to number of used iterations. (Caution: When building the graph, start the simulation with the same starting matrix.)

In [ ]:
num_letters=[]
M_initial=np.random.rand(4, 4)-0.5
for i in range(1, 100000, 25):
    M, e=trainlms(A, B, M_initial, ni, i)
    num_letters.append(np.sum(np.round(np.dot(M, A))==B))

plt.plot(list(range(1, 100000, 25)), num_letters)
plt.xscale("log")
plt.xlabel("Number of iterations")
plt.ylabel("Number of correct letters")
plt.show()

## 2.2.2 Effect of larger number of associations

This experiment demonstrates the capacity of the associative memory. What is the capacity of a $4\times 4$ correlation matrix based associative memory?

For additional pair '*auto*'-'*mrak*' create vectors $a_5$ and $b_5$ as explained in the previous part of the exercise. Create new matrices A and B with dimensions $4$ (rows) $\times$ $5$ (columns) in the same way as previously explained. Initialize the matrix $\mathbf{M}$ with random starting values.

In [ ]:
a5=real("auto")
b5=real("mrak")

A=np.hstack([a1, a2, a3, a4, a5])
B=np.hstack([b1, b2, b3, b4, b5])

M=np.random.rand(4, 4)-0.5

Use the *trainlms* function in the following way:

In [ ]:
ni=0.9999/max(np.linalg.eig(np.dot(A, A.T))[0])
M, e=trainlms(A, B, M, ni, 100000)
print(np.sum(np.round(np.dot(M, A))==B))
print(e[-1])

**Tasks**

1. How many iterations did you use?

Pokušao sam sa 10k, 100k i 1m iteracija da vidim ima li razlike.
2. How many characters were memorized correctly?

2
3. What is the SSE error?

Zbroj kvadratnih razlika od prosječne vrijednosti skupa za svaki element, ovdje je ovijek oko 219.
4. What happens if we call the function from the beginning?

Onda ponovo sa trainlms učimo, ali ne dolazi do drugačijih rezultata.
5. How many characters are correctly memorized now and how large is the mistake? Is there any difference and why?

Pogreška je još uvijek jednake veličine tj samo su 2 znaka točno memorirana. Razlike nema ni nakon dodatnog učenja jer su vjerojatno dodavanjem dodatnih stupaca izgubljeni neki podatci i s nikakvom količinom učenja nebi ih mogli vratiti.
6. Is it possible to train this network in order to memorize all five associations?

Ne
7. Why? (Explain the previous answer) 

Dodavanjem dodatnih stupaca i povečavanjem broja vektora iznad postavljene veličine od 4x4 mjenjamo prije upisane informacije i zato ne možemo doći do ispravno zapisanih poruka i karaktera.